exclude:
    - vendor
    - slides/reveal.js/plugin/markdown/example.md
    - slides/reveal.js/plugin/reveal.js-menu/README.md
    - slides/reveal.js/plugin/reveal.js-quiz/README.md
    - slides/reveal.js/test/simple.md
    - slides/reveal.js/css/theme/README.md
# theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v8.5.2
lang: es-es
timezone: Europe/Madrid
accent_color: '#8f5536'
accent_image: assets/img/sidebar-bg.jpg
color: '#8f5536'
logo: assets/logo.png
url: https://pro.iesdonana.org
tagline: Programación
baseurl: ''
google_analytics: UA-174272940-1
plugins:
  - jekyll-avatar
defaults:
  - scope:
      path: informacion-general.md
    values:
      menu: true
      order: 1
  - scope:
      path: objetivos-generales.md
    values:
      menu: true
      order: 2
  - scope:
      path: resultados-aprendizaje-criterios-evaluacion.md
    values:
      menu: true
      order: 3
  - scope:
      path: diapositivas.md
    values:
      menu: true
      order: 4
  - scope:
      path: about.md
    values:
      menu: true
      order: 5
