source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-theme-hydejack'
gem 'jekyll-avatar'
gem "nokogiri", ">= 1.14.3"
gem "commonmarker", ">= 0.23.10"
gem "activesupport", ">= 6.1.7.5"

gem "webrick", "~> 1.8"
